# Generated by Django 5.0.7 on 2025-06-25 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('Treasurer', 'Treasurer'), ('Administrator', 'Administrator')], max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committeeic', models.CharField(max_length=100, unique=True)),
                ('fullname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=200)),
                ('eventdesc', models.TextField()),
                ('eventdate', models.DateField()),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masjid.committee')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('amountrequested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requestdate', models.DateTimeField(auto_now_add=True)),
                ('requestedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masjid.committee')),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masjid.event')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('expenseid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('recordedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masjid.admin')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('reportid', models.AutoField(primary_key=True, serialize=False)),
                ('generateddate', models.DateTimeField(auto_now_add=True)),
                ('reportfile', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generatedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masjid.admin')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('incomeid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('recordedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masjid.admin')),
            ],
        ),
    ]
