# Generated by Django 5.0.7 on 2025-06-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
